apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <hpaName>
  namespace: <namespace>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <deploymentName>
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 65
