apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: "standard"  # Must match StatefulSet storageClassName
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # This path is specific to the Kubernetes node filesystem; update as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: "standard"  # Must match PV storageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
