apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ebs.csi.aws.com           # EKS-specific CSI driver for AWS EBS
parameters:
  type: gp2                             # Specify EBS volume type: gp2, gp3, io1, etc.
  fsType: ext4                          # Default file system for Linux
  encrypted: "true"                     # Enable encryption if needed
reclaimPolicy: Retain                   # Retain the PV after the PVC is deleted
volumeBindingMode: WaitForFirstConsumer # Ensures PV and pod are in the same Availability Zone
